### ISSUE TITLE
TRACK_REMOVED not fired between mobile Safari and laptop Chrome

### ISSUE THREAD

**Issue by eltonlin1998** [jitsi/lib-jitsi-meet#1399] opened 2020-11-09 06:26 UTC
## Description
When I connect to conference with iPhone Safari and Surface Book Chrome and start toggling the camera, TRACK_REMOVED does not fire correctly. I describe the 2 problems below. 

## Current behavior
**Problem 1/2: Toggling camera on laptop**
Initially, sharing the Surface Book Chrome camera to iPhone Safari works (although sometimes it doesn't but that's a separate problem). However, when turning off the camera, TRACK_REMOVED is not fired for iPhone, so the video simply freezes. But if I toggle the laptop camera on again, TRACK_REMOVED and TRACK_ADDED is fired *together*, and so in that sense turning on the camera _kind of works_.

**Problem 2/2: Toggling camera on iPhone**
Initially, sharing from iPhone to Surface Book works. But when I toggle off the phone camera, TRACK_REMOVED is not fired for the laptop, so the video simply freezes. If I toggle the iPhone camera on again, the track simply resumes and stops freezing, but unlike the first problem, TRACK_REMOVED and TRACK_ADDED is never fired again, it's simply the same track that is getting restarted. 

**A separate problem: Sharing camera from laptop to iPhone**
 Sometimes (undeterministically), if I turn on camera for Surface Book Chrome, the iPhone Safari receives an empty track (the <video> is simply white and has no data, even though it's taking up space)

## Expected Behavior
I expect the TRACK_REMOVED event to be fired whenever the remote user turns off the camera, no matter which device and what browser. I also expect that sharing the camera from laptop to iPhone will always work on the first time, and would not require 2-3 re-toggles. 

## Possible Solution
I tried listening for "LOCAL_TRACK_STOPPED" for remote tracks and use that as a fake substitute for "TRACK_REMOVED". However, that isn't fired either. 

I tried calling "track.setEffect(undefined)" for each track, before calling "track.dispose()", but it didn't make a differene. 

I tried using the full config copied from https://meet.jit.si/config.js, except with 

`  ...
     serviceUrl: 'https://meet.jit.si/http-bind?room=' + "<put-future-room-id-here>",
     clientNode: 'http://jitsi.org/jitsimeet',
`

I tried using different versions of lib-jitsi-meet.js (from the example, from the URL, and by building the .min.js file directly from Github)

I'm currently trying to reverse-engineer from Jitsi Meet, because I did the same experiment on Jitsi Meet and *it works*, so it could be certain config values / versions of lib-jitsi-meet / their logic that somehow circumvents this bug. 

## Steps to reproduce
Open https://jitsi-vue-playground.web.app/ and simply perform the steps described above. 
The source code is: https://github.com/eltonlin1998/jitsi-vue-experiment

# Environment details
lib-jitsi-meet.min.js was built from the repo during October
node v10.10.0 and 7.0.7

Lastly, because I'm emotionally invested in this, I want to create a plugin / new example.js that works for all browsers and just works after npm install for lib-jitsi-meet for anyone who uses Jitsi / Vue to use. Would that be useful? How would I get started on that? 

Thanks for reading : )

**Comment by ashitikov** [comment] 2020-11-09 07:34
#1105 Could be related

**Comment by samuelsimoes** [comment] 2020-12-17 19:34
The same can be reproduced toggling the camera from Firefox 83 on Linux.

**Comment by samuelsimoes** [comment] 2020-12-17 20:07
Some that I noticed doing some tests.

If you:
 
1. open the conference on https://meet.jit.si
2. start a video track on Firefox through an app using lib-jitsi-meet lib and then stop it

The Meet Jitsi interface also doesn't receive the track stoppage event, so it looks to be an issue when removing the video track on Firefox not sending the information to the server, because even reloading the Meet Jitsi interface it still showing the track that doesn't exist anymore.

Now the interesting part is that as @eltonlin1998 reported, it works fine between browsers when using only the Meet Jitsi interface. How the Meet Jitsi is handling the video track removal? (I will try to understand it) :thinking:

**Comment by eltonlin1998** [comment] 2021-01-01 03:34
I'm going to try it!

**Comment by eltonlin1998** [comment] 2021-01-03 09:21
> Edit 1: after some research, I finally found that Meet Jitsi doesn't remove the track, instead it mutes it, ok. This will be a workaround.

Hi samuelsimoes, which particular files and line numbers from Meet Jitsi's repository handles the video track removal?

**Comment by jerry2013** [comment] 2021-02-25 17:38
Based on my limited testing, this happens between plan-b (chrome) and all others browsers using unified plan.

**Comment by jallamsetty1** [comment] 2021-06-01 14:19
Closing this issue since it has been fixed here - https://github.com/jitsi/lib-jitsi-meet/commit/4e5804f96595d4656da0f351adb5cb87d630d50b

**Closed by jallamsetty1** 2021-06-01 14:19 UTC
