### ISSUE TITLE
[Edge] Wrong BWE (JVB reports bad connectivity)

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#501] opened 2017-06-05 16:15 UTC
When testing with Chrome, Firefox and Edge, most of the time the JVB reports a terribly bandwidth availability on Edge (so in Chrome and Firefox I read "Edge is having connectivity issues" with frozen grayed video and so on).

I'm on a good network so I expect that the mechanism used by the JBV to estimate browsers bandwidth does not work fine with Edge. 

NOTE: Edge does not support DataChannel so statistics are also missing. But I don't think this is related to the reported issue.

NOTE: The current implementation of lib-jitsi-meet in Edge does not support P2P mode so, for sure, this is always through the JVB.

/CC @gpolitis

**Comment by gpolitis** [comment] 2017-06-05 16:24
Thanks for reporting Inaki. I’m not sure whether your diagnosis is correct or not, but the symptom clearly indicates an issue. Network connectivity issues usually means that the VP8 stream is broken. I’m wondering whether it’s related to the VP8 rewriting issue. Does the connectivity issue happen with VP8 rewriting on? Does it happen every time?

**Comment by ibc** [comment] 2017-06-05 16:31
The connectivity issue also happens with the VP8 rewriting disabled. Exactly as when enabled, but having it disabled I can properly see video from Edge (those times I don't see the video frozen due to "bad connectivity").

**Comment by gpolitis** [comment] 2017-06-05 16:34
I see, are you able to confirm whether Edge is sending video or not when the problem occurs?

**Comment by ibc** [comment] 2017-06-05 16:34
> I see, are you able to confirm whether Edge is sending video or not when the problem occurs?

Let me check once my testing Edge server becomes usable for testing :)

**Comment by gpolitis** [comment] 2017-06-05 16:38
Awesome, it would also be helpful to 1) have RTP packet recording and 2) a heap dump of the bridge (you can just execute /usr/share/jitsi-videobridge/collect-dump-logs) and 3) update your bridge to the latest that includes a bunch of improvements and fixes. Thanks!

**Comment by ibc** [comment] 2017-06-05 16:45
For now just this info:

Indeed, when I get "Edge connectivity issues" warning in Chrome, and according to chrome://webrtc-internals, I **do not** receive VP8 packets. I mean: no one during the "connectivity" issue.

Now I need to check what happens in Edge side.

**Comment by ibc** [comment] 2017-06-06 17:35
Hi, I've ported copy&pasted the jitsi Edge `RTCPeerConnection` shim into my [mediasoup demo](https://demo.mediasoup.org).

mediasoup does not perform VP8 rewriting (nor JVB since I've disabled it), and there is no simulcast. Anyhow, the video is smooth between all the participants and Chrome's video is automatically rendered in Edge. When in Jitsi-meet with JVB, it takes several seconds for the Chrome's video to start being rendered in Edge.

Here a video: http://public.aliax.net/jitsi-edge-peerconnection-in-mediasoup.mp4

**Comment by gpolitis** [comment] 2017-06-06 17:40
Clearly there's a problem with the JVB. Please don't forget to gather the logs when you get a chance, otherwise there's nothing we can do.

**Comment by ibc** [comment] 2017-06-08 16:23
Here a ZIP with a jvb.log and a pcap (as captured by the JVB). It's a room with Chrome and Edge:

[chrome-edge-1.zip](https://github.com/jitsi/lib-jitsi-meet/files/1061542/chrome-edge-1.zip)


To simplify, simulcast and RTX have been disabled in lib-jitsi-meet (by hacking `RTCBrowserType.js`).

In the JVB, `org.jitsi.videobridge.ENABLE_VP8_PICID_REWRITING` is set to `false` (otherwise the video received by Edge is 200% crappy/useless/corrupted as seen [here](https://github.com/jitsi/lib-jitsi-meet/pull/473#issuecomment-300573271)).

The result is that Edge almost automatically displays/renders the vidoe from Chrome (and vice-versa) but in Chrome I see "Edge is having connectivity problems" most of the time (grayed screen) and, in Edge, the quality of the video from Chrome is far from perfect.

*NOTES:*

* If I let simulcast enabled for Chrome in lib-jitsi-meet, then the video from Chrome takes over 10-20 seconds to be rendered in Edge.
* In `chrome://webrtc-internals` I don't see any PLI or FIR received in the VP8 sender of Chrome.

Here some info of the room:

### CHROME

* local addr: 2.136.180.11:49200
* ssrc video: 549376753

### EDGE

* ssrc video: 1597635261


### Remote SDP offer in Chrome

```
v=0
o=- 1923518516 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS mixedmslabel
a=group:BUNDLE audio video data
m=audio 10000 RTP/SAVPF 111 103 104 126
c=IN IP4 52.90.94.230
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:40k521bi45di79
a=ice-pwd:7m5f146jkl8iufi1v8tq832rvh
a=fingerprint:sha-1 14:D4:12:50:60:E7:1A:7C:3C:C5:33:C5:69:F7:3D:AF:9F:B1:52:AA
a=candidate:1 1 ssltcp 2130706431 10.186.3.47 4443 typ host generation 0
a=candidate:3 1 udp 2130706431 10.186.3.47 10000 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 52.90.94.230 4443 typ srflx raddr 10.186.3.47 rport 4443 generation 0
a=candidate:4 1 udp 1677724415 52.90.94.230 10000 typ srflx raddr 10.186.3.47 rport 10000 generation 0
a=ssrc:2236682482 cname:mixed
a=ssrc:2236682482 msid:mixedmslabel mixedlabelaudio0
a=ssrc:2236682482 mslabel:mixedmslabel
a=ssrc:2236682482 label:mixedlabelaudio0
a=ssrc:3378395145 cname:jitsi-ortc-cname-86018
a=ssrc:3378395145 msid:508153F4-4724-4ECD-96F8-4E478BB1E698 3F06B970-B4F4-4925-BEB6-239694B3A859
a=rtcp-mux
m=video 10000 RTP/SAVPF 100 107 101
c=IN IP4 52.90.94.230
a=rtpmap:100 VP8/90000
a=rtpmap:107 h264/90000
a=rtpmap:101 VP9/90000
a=fmtp:100 x-google-start-bitrate=800
a=fmtp:107 x-google-start-bitrate=800
a=fmtp:101 x-google-start-bitrate=800
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:40k521bi45di79
a=ice-pwd:7m5f146jkl8iufi1v8tq832rvh
a=fingerprint:sha-1 14:D4:12:50:60:E7:1A:7C:3C:C5:33:C5:69:F7:3D:AF:9F:B1:52:AA
a=candidate:1 1 ssltcp 2130706431 10.186.3.47 4443 typ host generation 0
a=candidate:3 1 udp 2130706431 10.186.3.47 10000 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 52.90.94.230 4443 typ srflx raddr 10.186.3.47 rport 4443 generation 0
a=candidate:4 1 udp 1677724415 52.90.94.230 10000 typ srflx raddr 10.186.3.47 rport 10000 generation 0
a=ssrc:1458829241 cname:mixed
a=ssrc:1458829241 msid:mixedmslabel mixedlabelvideo0
a=ssrc:1458829241 mslabel:mixedmslabel
a=ssrc:1458829241 label:mixedlabelvideo0
a=ssrc:1597635261 cname:jitsi-ortc-cname-86018
a=ssrc:1597635261 msid:50AACBBA-6257-4D0C-8B35-41012EA56DFD 751945FF-E0A2-4A56-92C9-E1673F3DD8D7
a=rtcp-mux
m=application 10000 DTLS/SCTP 5000
c=IN IP4 52.90.94.230
a=setup:actpass
a=mid:data
a=ice-ufrag:40k521bi45di79
a=ice-pwd:7m5f146jkl8iufi1v8tq832rvh
a=fingerprint:sha-1 14:D4:12:50:60:E7:1A:7C:3C:C5:33:C5:69:F7:3D:AF:9F:B1:52:AA
a=candidate:1 1 ssltcp 2130706431 10.186.3.47 4443 typ host generation 0
a=candidate:3 1 udp 2130706431 10.186.3.47 10000 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 52.90.94.230 4443 typ srflx raddr 10.186.3.47 rport 4443 generation 0
a=candidate:4 1 udp 1677724415 52.90.94.230 10000 typ srflx raddr 10.186.3.47 rport 10000 generation 0
a=sctpmap:5000 webrtc-datachannel 1024
```

### Local SDP answer in Chrome

```
v=0
o=- 8263791362785685785 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS 4c562840-7083-4221-a8df-8cfb3d6a3ed3
a=group:BUNDLE audio video data
m=audio 59229 RTP/SAVPF 111 103 104 126
c=IN IP4 192.168.1.114
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:passive
a=mid:audio
a=sendrecv
a=ice-ufrag:VFuA
a=ice-pwd:D41KKLlGDbAM35OJd0W88ejC
a=fingerprint:sha-256 1E:EF:B1:BD:A0:DA:47:44:43:23:68:2C:9C:A3:1B:BF:38:8B:E9:F9:71:D2:A8:27:C2:8B:2B:C4:EC:37:82:08
a=candidate:27784895 1 udp 2122260223 192.168.1.114 59229 typ host generation 0 network-id 1 network-cost 10
a=candidate:1327761999 1 tcp 1518280447 192.168.1.114 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ssrc:286718648 cname:WLdGMF4gWtwfB+k2
a=ssrc:286718648 msid:902d5886-b174-4d22-9a24-32473cd9fd34 472bdbe5-29ba-46e7-b585-0b76bfe95258
a=ssrc:286718648 mslabel:902d5886-b174-4d22-9a24-32473cd9fd34
a=ssrc:286718648 label:472bdbe5-29ba-46e7-b585-0b76bfe95258
a=rtcp-mux
m=video 9 RTP/SAVPF 100 107 101
c=IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtpmap:107 h264/90000
a=rtpmap:101 VP9/90000
a=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:passive
a=mid:video
a=sendrecv
a=ice-ufrag:VFuA
a=ice-pwd:D41KKLlGDbAM35OJd0W88ejC
a=fingerprint:sha-256 1E:EF:B1:BD:A0:DA:47:44:43:23:68:2C:9C:A3:1B:BF:38:8B:E9:F9:71:D2:A8:27:C2:8B:2B:C4:EC:37:82:08
a=ssrc:549376753 cname:WLdGMF4gWtwfB+k2
a=ssrc:549376753 msid:4c562840-7083-4221-a8df-8cfb3d6a3ed3 a22b1cad-e15a-4021-9012-7dd73c6c526d
a=ssrc:549376753 mslabel:4c562840-7083-4221-a8df-8cfb3d6a3ed3
a=ssrc:549376753 label:a22b1cad-e15a-4021-9012-7dd73c6c526d
a=rtcp-mux
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=setup:passive
a=mid:data
a=ice-ufrag:VFuA
a=ice-pwd:D41KKLlGDbAM35OJd0W88ejC
a=fingerprint:sha-256 1E:EF:B1:BD:A0:DA:47:44:43:23:68:2C:9C:A3:1B:BF:38:8B:E9:F9:71:D2:A8:27:C2:8B:2B:C4:EC:37:82:08
a=sctpmap:5000 webrtc-datachannel 1024
```

**Comment by gpolitis** [comment] 2017-06-08 16:26
Thanks for the logs Inaki! I'll have a look and update here.

**Comment by gpolitis** [comment] 2017-06-12 16:33
Hi @ibc,

As a first observation, does your Chrome (local addr: 2.136.180.11:49200) run behind a firewall? It's connecting through TCP whereas Edge connects through UDP. That can explain the terrible video quality from the Chrome participant (I even think there was a bug in Chrome congestion control when it runs over TCP).

I had a look at the pcap file and I have a suspicion what might be wrong. I've tweaked some params on your bridge and I've also updated it.

Could you please give it another try?

**Comment by ibc** [comment] 2017-06-12 16:35
Wow, is it true that Chrome connected on TCP? I really assumed that it was connected on UDP!
Will check tomorrow again and let you know. Thanks!

**Comment by gpolitis** [comment] 2017-06-12 16:42
It's running over TCP, at least in the pcap file that I analyzed. I'm sure I can find bugs in the bridge, so I'll keep looking and keep you posted. Thanks for planning to check!

**Comment by gpolitis** [comment] 2017-06-12 22:06
When you get to it, could you also please try with simulcast and picid rewriting enabled? (and collect pcap and logs) I would like to have a look at that.

**Comment by ibc** [comment] 2017-06-12 22:08
Sure, will do tomorrow and let you know.

**Comment by gpolitis** [comment] 2017-06-12 23:08
1. Even without simulcast, Chrome is sending different picture ID offsets for different resolutions (remember, in a single stream you can adapt the bitrate by reducing/increasing the resolution).
2. The purpose of pic id rewriting is to provide a monotonically strictly increasing sequence of picture ids.

I suspect Edge expects a jump in the picture ID to reset the resolution information of a stream, whereas the correct thing to do would be to grab the resolution information from the first packet of a keyframe. This would explain why when you enable pic id rewriting the video received by Edge is 200% crappy/useless/corrupted.

In order to confirm this suspicion, @ibc could you please disable simulcast and activate picture id rewriting and check whether you're able to reproduce the 200% crappy/useless/corrupted video on Edge?

**Comment by gpolitis** [comment] 2017-06-12 23:31
I'm using Chrome 60 (latest beta) and, if I disable simulcast, I don't see any jumps in the picture IDs, which is different from what I see in the captured pcap file hmm... Which Chrome version are you using?

**Comment by ibc** [comment] 2017-06-14 10:58
I'm using latest chrome stable in OS X, which is 58.0.3029.110.

I will try disabling simulcast (in lib-jitsi-meet) and re-enable picture Id rewriting in JVB today and let you know.

**Comment by ibc** [comment] 2017-06-23 14:02
NOTE: The "Edge is having connectivity issues" problem happens **much less** if `org.jitsi.videobridge.TRUST_BWE` is set to `false`.

**Comment by ibc** [comment] 2017-06-27 16:08
BTW I confirm that, when pinning a peer in Edge, such a peer receives a PLI (/cc @saghul)

**Comment by saghul** [comment] 2017-06-30 05:45
I have yet to experience this. I'm going to tentatively close it since I doubt it's an Edge related issue.

**Closed by saghul** 2017-06-30 05:45 UTC
