### ISSUE TITLE
Stats are hidden after a second

### ISSUE THREAD

**Issue by ibc** [jitsi/lib-jitsi-meet#527] opened 2017-06-28 14:46 UTC
In the new UI, when doing mouse "hover" to show the stats of a peer, the layer is hidden after ~1 second. It seems to me that it's hidden when calling again to `pc.getStats()`.

**Comment by virtuacoplenny** [comment] 2017-06-28 17:13
I'm not able to reproduce this issue on Firefox, Safari, Chrome, or IE10. You're simply joining a call that has at least another participant and mousing over a connection indicator (the connection bars in the thumbnail video) to display the connection stats? Is this occurring across browsers and is it occurring consistently? The new UI you're referring to is the vertical filmstrip? Are you on the latest version of jitsi-meet?

**Comment by gpolitis** [comment] 2017-06-29 10:53
I'm not able to repro it either, unless I misunderstood the bug report.

**Comment by ibc** [comment] 2017-06-29 12:37
> you're simply joining a call that has at least another participant and mousing over a connection indicator (the connection bars in the thumbnail video) to display the connection stats?

Yes, but specifically I click on the "Show more" text in the local user (which displays the local IP:port, etc).

> Is this occurring across browsers and is it occurring consistently?

Yesterday I got this happening in both Chrome and Edge.

> The new UI you're referring to is the vertical filmstrip?

Yes.

> Are you on the latest version of jitsi-meet?

I updated it two days ago.

However, I'm not able to reproduce the issue in https://meet.jit.si.

Let's close the issue. I'll reopen it if it happens again by providing more useful info.

**Comment by virtuacoplenny** [comment] 2017-06-29 15:37
I'll have another try at reproducing it today. It wouldn't surprise me if you can't repro on meet just because that environment is fairly behind jitsi-meet master. My current suspicion is also that vertical filmstrip isn't related to the problem because that vertical filmstrip mode is done mostly through css changes around the small video containers and not much change in javascript logic, and javascript logic is what controls the display of the popover/connection stats.

**Comment by ibc** [comment] 2017-06-29 16:11
NOTE: It seems that it may just happen in Edge.

**Comment by virtuacoplenny** [comment] 2017-06-29 16:56
Is there an environment or branch I can use to test connection stats display on Edge? The stats wouldn't have to be accurate, of course.

**Comment by ibc** [comment] 2017-06-29 17:02
edge.jitsi.net has the latest Edge stuff.

**Comment by virtuacoplenny** [comment] 2017-06-29 17:57
Are there any steps to getting stats to work on edge? My stats remain as N/A.

**Comment by ibc** [comment] 2017-06-29 19:42
Unfortunately it's not currently possible to get local stats: https://github.com/jitsi/lib-jitsi-meet/issues/523#issuecomment-311677339

**Comment by saghul** [comment] 2017-06-30 12:33
I'm going to close this since I cannot reproduce it. I've seen it happen to @ibc but I'm calling shenanigans :-)

**Closed by saghul** 2017-06-30 12:33 UTC
