### ISSUE TITLE
Optimize for npm install

### ISSUE THREAD

**Issue by joshfarrant** [jitsi/lib-jitsi-meet#484] opened 2017-05-16 15:21 UTC
Apologies if this has been discussed already, but I can't find any other conversations on this topic.

Is there a reason that this package isn't really optimized for being installed through npm? I'm trying to integrate this into a React app and I'm having a bit of a hard time getting everything up and running.

It would be nice if we could simply `npm install lib-jitsi-meet` within a project and then just `import JitsiMeetJS from 'lib-jitsi-meet';`, however this currently doesn't seem to be possible.

Obviously the package isn't currently published to npm, but that's not an issue as we can install directly from this repo. Doing that, however, seems to do three things. It...

1. Clones the repo
2. Installs production dependencies only, not devDependencies
3. Runs `postinstall` npm script (`webpack -p`) and fails because of missing devDependencies.

Navigating to `<my-react-project>/node_modules/lib-jitsi-meet` and running `npm install` manually does install these devDependencies and run the `postinstall` script successfully, creating `lib-jitsi-meet.min.js` and `lib-jitsi-meet.min.map`.

At this point, trying to `import JitsiMeetJS from 'lib-jitsi-meet';` creates errors as the `"main"` property of the `package.json` references the `./index.js` file, rather than the built (and transpiled) `lib-jitsi-meet.min.js` file created by webpack.

If we update the `"main"` property of the `package.json` to be `./lib-jitsi-meet.min.js` then `import JitsiMeetJS from 'lib-jitsi-meet';` does in fact import `JitsiMeetJS` as expected. Now, however, we get a `ReferenceError: Strophe is not defined`.

Adding `import strophe;` does resolve this, however we then get `Missing strophe-plugins (disco and caps plugins are required)!`. At this point it's clear that the strophe and strophe-plugins modules aren't included in the `lib-jitsi-meet.min.js` file that webpack builds, even though they are listed as project dependencies. Is there a reason that the choice was made to require these modules globally, rather than just importing them whenever they're needed? From looking through the codebase it looks like the same goes for jQuery.

This all can be solved by the user including `<script>` tags in their html, as you recommend, or possibly by using webpack's `ProvidePlugin`, but it seems like it would be far nicer to try to do as much as possible when packaging the module in the first place.

Interested to hear your thoughts on this.

**Comment by damencho** [comment] 2017-05-16 16:05
lib-jitsi-meet moves in sync with all the other server-side components jicofo and videobridge. That's the reason you need sourcing lib-jitsi-meet as this is part of the deployment. Embedding lib-jitsi-meet in your app and then updating the backend you risk to break stuff.
This is the main reason and this is how jitsi-meet currently use it.

**Comment by joshfarrant** [comment] 2017-05-17 08:47
I understand that it compatibility with the backend is a priority, but I don't quite understand why a module bundler is being used but libraries that don't look like they're going to change much (jQuery, strophe) aren't added in too. I wouldn't think that including them in the bundled file would cause any compatibility issues as the libraries aren't changing, you're just pulling them in yourself at build-time instead of relying on the user bringing them in.

I should note - I may be missing something here as I'm new to lib-jitsi-meet, so apologies if that's the case. I'm just trying to understand if there's a fundamental reason that I can't pull the bundled file in and nothing else, as that seems like the simplest way to use this library

If this doesn't line up with this repo's goals then I'm happy to fork and play around with this myself. I will likely be using a fixed version of videobridge in the project I'm building, so ongoing compatibility may not be an issue, although I see no reason why the fork couldn't be kept up-to-date with this main repo.

**Comment by saghul** [comment] 2017-05-17 12:09
@joshfarrant Historically those dependencies have been provided by the app bundle, while lib-jitsi-meet remained a standalone bundle.

@damencho I wonder if we can improve on this when Webpack 2 lands, since it does tree-shaking, so we could potentially depend on libraries on both places and have Webpack dedupe them?

**Comment by webintoit** [comment] 2017-07-28 13:37
@joshfarrant 
1) Move all dependencies needed to build project, except testing suite from `dev` to ordinary list
2) add `"lib-jitsi-meet": "yourgithublink/lib-jitsi-meet"` to your package.json
3) In your project's package.json add ljm to `browser` section: 
    ` "ljm": "./node_modules/lib-jitsi-meet/lib-jitsi-meet.min.js"`
4) require it in ur project  `let ljm = require("ljm")` (or import it if you`re using webpack 2)

It works for me.

**Comment by Kukunin** [comment] 2017-11-12 23:17
My two pennies: it shouldn't run `webpack` in `postinstall` at all, since webpack is ran in the application itself, and it's able to load all dependencies. This way my app will take only files I need not the whole library.

This is how a typical NPM package is distributed.

**Comment by Kukunin** [comment] 2017-11-12 23:22
BTW, you can run `npm install --ignore-scripts` to avoid `postinstall`. It doesn't solve all problems, but at least you can install the package

**Comment by tiofabby** [comment] 2018-05-11 09:35
you can do a 'npm install lib-jitsi-meet' and use it as a module

**Comment by sapkra** [comment] 2019-05-15 06:10
> you can do a 'npm install lib-jitsi-meet' and use it as a module

This version is extremely old and has some bugs. Like @saghul mentioned [here](https://community.jitsi.org/t/error-strophe-referenceerror-b64-sha1-is-not-defined/16334) we have to use the GitHub version.

The problem with the GitHub version is that the build is failing when you try to install it because `@babel/plugin-proposal-export-namespace-from` and `string-replace-loader` cannot be resolved so we have to install it manually.
I would appreciate it when there will be an official version published on npm.

Additionally we have to install and import `strophe`, `strophejs-plugin-caps`, `strophejs-plugin-disco` and `jquery` otherwise it will crash. It would also be nice to remove jQuery entirely.

The experience to install this library was really bad and there is much room for improvements.

**Comment by methodbox** [comment] 2019-11-22 19:20
I think there is an actual issue here in that there doesn't seem to be a way to hook into the API to, and I quote, "use Jitsi Meet API to create Jitsi Meet video conferences with a custom GUI".

How the hell can I use Jitsi to create a custom GUI if I can't load it as an import into, for example, my React development environment?

The only way to use this seems to be to add it as a script in an HTML file. That makes it way too hard to make API calls inside my React code.

Can someone give some insight as to how this can be done?

**Comment by ajorkowski** [comment] 2019-11-22 20:07
We actually use a 100% custom UI (using React) over lib-jitsi-meet. Just thought I'd share how I do our implementation.

We actually deploy Jitsi (using the docker lib) and manually import the script from docker at runtime. I think this actually works better because then the deployment of jitsi and the lib that uses it always matches up. The only tricky thing that I have found is that jitsi depends on a global jquery... so I need to import that in (this is the only lib in our project that uses jquery). Some code below:

Note that `config.jitsi.lib` would be something like `https://video.domain.com/lib-jitsi-meet.js`. ie the location of the meet lib in the deployed docker instance

```
/* global JitsiMeetJS */
import $ from 'jquery';
import { installScript } from 'utils/dom';
import config from 'config';
...

let _jistiPromise = null;
function _getJitsi() {
  if (!_jistiPromise) {
    window.$ = $;
    _jistiPromise = installScript(config.jitsi.lib, true)
      .then(() => {
        // Set the log level, and forward errors to app insights
        JitsiMeetJS.setLogLevel(IS_DEBUG ? JitsiMeetJS.logLevels.DEBUG : JitsiMeetJS.logLevels.ERROR);
        JitsiMeetJS.addGlobalLogTransport({
          error: (file, location, msg) => {
            const err = new Error(file + ' ' + location);
            log.error(msg, err, { Platform: 'Telehealth' });
          }
        });
        JitsiMeetJS.init(config.jitsi);
        devices.init(); // This is my code
        return null;
      })
      .catch(err => {
        _jistiPromise = null;
        throw err;
      });
  }
  return _jistiPromise;
}
```

And here is my `installScript` function

```
export function installScript(url, crossOrigin, id) {
  return new Promise((resolve, reject) => {
    var s = document.createElement('script');
    s.src = url;
    if (crossOrigin) { s.crossOrigin = 'anonymous'; }
    if (id) { s.id = id; }
    s.type = 'text/javascript';
    s.async = 'true';
    s.onload = resolve;
    s.onerror = function() { reject(new Error('Script load error')); };
    document.body.appendChild(s);
  });
}
```

**Comment by methodbox** [comment] 2019-11-22 20:38
@ajorkowski 

Thanks for the reply, but I’m still not clear how I might import the JitsiMeetJS from Jitsi into a React app.

You’re example seems to assume this is already done. For example, you call the function here, but you’ve not imported it from anything at the top.

```js
JitsiMeetJS.init(config.jitsi);
```

In my case we aren’t running anything similar to what your Docker config is; I’ll need to have imported it already, but using `lib-jitsi-meet`, building the min.js and importing this simply doesn’t work right.

I essentially need to use the API to make calls to a self-hosted Jitsi video bridge instance.

I can’t do this if the script is loading in index.html after my code is built, because I need to do it inside React components.

**Comment by damencho** [comment] 2019-11-23 12:49
@methodbox 
> In my case we aren’t running anything similar to what your Docker config is; I’ll need to have imported it already, but using `lib-jitsi-meet`, building the min.js and importing this simply doesn’t work right.

The idea is that lib-jitsi-meet is a library which follows backend, the best approach is to source it from the app. Embedding it in the app you may end up with a broken app when your backend updates.


> I can’t do this if the script is loading in index.html after my code is built, because I need to do it inside React components.

Why you cannot do this? This is how jitsi-meet is doing it.
https://github.com/jitsi/jitsi-meet/blob/master/index.html#L147
And jitsi-meet is a React app.

**Comment by methodbox** [comment] 2019-11-23 14:08
@damencho 
While that works, there is no way to work directly with the API inside VS Code.

This also means the script is being loaded statically.

You must understand what I’m asking for - it’s effectively loading this as a Node module.

Loading this script statically has many problems, and while you method may work technically, it also completely prevents me from using Typescript, looking up methods in VS Code and bundling you script in my build.

It also prevents me from doing things like writing unit tests that test before the build is complete; your code only exists in the browser.

Last it **completely** ignores the use of this API on the backend and in a Node-only app.

If you have a proper Node package along with the proper exports allowing use of your code as is done in the 21st century, I haven’t been able to find any documentation of it.

Everything I’ve found in other posts asking for this, your response has been to use the script tag, so I’m assuming Jitsi either doesn’t understand what is being requested or doesn’t want to provide a solution. Or maybe you just don’t want us to interface with your API in a way that most packages allow, I don’t know.

**Comment by methodbox** [comment] 2019-11-23 14:15
> @methodbox
> 
> > In my case we aren’t running anything similar to what your Docker config is; I’ll need to have imported it already, but using `lib-jitsi-meet`, building the min.js and importing this simply doesn’t work right.
> 
> The idea is that lib-jitsi-meet is a library which follows backend, the best approach is to source it from the app. Embedding it in the app you may end up with a broken app when your backend updates.
> 
> > I can’t do this if the script is loading in index.html after my code is built, because I need to do it inside React components.
> 
> Why you cannot do this? This is how jitsi-meet is doing it.
> https://github.com/jitsi/jitsi-meet/blob/master/index.html#L147
> And jitsi-meet is a React app.

Your comment that embedding it may result in it breaking simply doesn’t make sense (it’s also a cut and paste from another of your responses on here which is kind of insulting).

I’m not trying to embed Jitsi. I’m trying to use your API methods to create my own GUI.

I’m using a Parcel config to auto-load React and do development as is extremely common, and load your Jitsi API `external_api.min.js` into my project, but as said above, loading a script tag statically isn’t the same thing.

And yes, I realize if your API changes the code will break. I’m not clear how you would expect that to be any different based on loading your script statically or loading it in a project with a `require()` or ES6 `import`?

Also, API methods changing is just a basic part of maintaining code. How else would I be expected to create my own GUI wrapper around Jitsi and brand the app if I don’t use the API (which is exactly what your own docs suggest).

**Comment by methodbox** [comment] 2019-11-23 14:25
Can you at least provide or point me to a version of `external_api.min.js` which has not been minified?

We would rather convert and maintain a copy of this that is actually useful in development as a proper Node package and risk things breaking than deal with the current work around.

**Comment by damencho** [comment] 2019-11-23 15:13
> Your comment that embedding it may result in it breaking simply doesn’t make sense (it’s also a cut and paste from another of your responses on here which is kind of insulting).

This so not true. If you search the community forum, a month or two a user was complaining that his app stopped working and at the end, it turned out that the case was exactly that. The fact he was embedding the library in his app and after backend update, everything broke for him.



> And yes, I realize if your API changes the code will break. I’m not clear how you would expect that to be any different based on loading your script statically or loading it in a project with a `require()` or ES6 `import`?

Not these are not external API changes but changes in the API between the library and the backend, something you cannot verify by just building your app and resolving errors. 
This works as you will be downloading the appropriate version of the app on every run, so after updating backend you will download the correct version of the library that comes with that backend.

> Can you at least provide or point me to a version of `external_api.min.js` which has not been minified?

Now you switched asking about the iframe API, I got really confused I was with the impression we were discussing lib-jitsi-meet?
Iframe API code is here: https://github.com/jitsi/jitsi-meet/tree/master/modules/API

By the way FYI we are planning to start releasing lib-jitsi-meet to npmjs repo for every build of it as a pre-compiled library and be using those versions instead of github tags in jitsi-meet: https://github.com/jitsi/jitsi-meet/blob/master/package.json#L60
I suspect you will be able to use it from there. One of the first things that we will add to the Notes is the statement above, that the best approach is to source the library from the backend to avoid breakage.

Sorry, I'm not a JS specialist and I'm not so familiar with all the stuff you mention to be able to comment. I was just giving you the facts, what I know, trying to help, as we are already using the library in a big project and it works. If you don't like it, I'm sorry, I tried to help you and don't see how I insulted you.

**Comment by methodbox** [comment] 2019-11-23 15:57
> > Your comment that embedding it may result in it breaking simply doesn’t make sense (it’s also a cut and paste from another of your responses on here which is kind of insulting).
> 
> This so not true. If you search the community forum, a month or two ago a user was complaining that his app stopped working and at the end, it turned out that the case was exactly that. The fact he was embedding the library in his app and after backend update, everything broke for him.
> 
> > And yes, I realize if your API changes the code will break. I’m not clear how you would expect that to be any different based on loading your script statically or loading it in a project with a `require()` or ES6 `import`?
> 
> Not these are not external API changes but changes in the API between the library and the backend, something you cannot verify by just building your app and resolving errors.
> This works as you will be downloading the appropriate version of the app on every run, so after updating backend you will download the correct version of the library that comes with that backend.
> 
> > Can you at least provide or point me to a version of `external_api.min.js` which has not been minified?
> 
> Now you switched asking about the iframe API, I got really confused I was with the impression we were discussing lib-jitsi-meet?
> Iframe API code is here: https://github.com/jitsi/jitsi-meet/tree/master/modules/API
> 
> By the way FYI we are planning to start releasing lib-jitsi-meet to npmjs repo for every build of it as a pre-compiled library and be using those versions instead of github tags in jitsi-meet: https://github.com/jitsi/jitsi-meet/blob/master/package.json#L60
> I suspect you will be able to use it from there. One of the first things that we will add to the Notes is the statement above, that the best approach is to source the library from the backend to avoid breakage.
> 
> Sorry, I'm not a JS specialist and I'm not so familiar with all the stuff you mention to be able to comment. I was just giving you the facts, what I know, trying to help, as we are already using the library in a big project and it works. If you don't like it, I'm sorry, I tried to help you and don't see how I insulted you.

Right now it’s unclear if the best approach to creating a custom GUI is using the iframe API or the lib-jitsi-meet.

I think most people who are using a self-hosted video bridge would like to be able to use an NPM package to add the API methods for ease of development, and likely want to effectively wrap the iframe and make it their own.

The lib-jitsi-meet API seems to only be useful if you’re recreating what the iframe does from scratch, which is fine, but the approach you suggest taking in releasing this on NPM should be applied to the iframe API, too.

I will take a look at the source you linked.

The “insult” I referred to is providing the same answer provided to others when asking a similar but different question. No real offense taken.

**Comment by damencho** [comment] 2019-11-23 16:06
> Right now it’s unclear if the best approach to creating a custom GUI is using the iframe API or the lib-jitsi-meet.

So the iframe API doc says: "You can use the Jitsi Meet API to embed Jitsi Meet into your application.", while the lib-jitsi-meet one says "You can use Jitsi Meet API to create Jitsi Meet video conferences with custom GUI.". I agree that both mention `Jitsi Meet API` which may be confusing, but both work in the context of their project.

So the iframe API is to embed the whole jitsi-meet in your APP, you can also use meet.jit.si deployment embedding it in your app as the document states. While the other one(lib-jitsi-meet) is low-level representation of conferences where you can create the connection and conference, etc. and embed the logic in your UI, and the example of doing that using the library is jitsi-meet.

**Comment by sapkra** [comment] 2019-11-24 09:51
> By the way FYI we are planning to start releasing lib-jitsi-meet to npmjs repo for every build of it as a pre-compiled library and be using those versions instead of github tags in jitsi-meet: https://github.com/jitsi/jitsi-meet/blob/master/package.json#L60

@damencho Great to hear that there will be some progress. I've also ask in the community forum but didn't got a reply.
https://community.jitsi.org/t/publish-lib-jitsi-meet-to-npm-as-jitsi-lib-jitsi-meet/20310

**Comment by saghul** [comment] 2019-11-25 06:39
Sorry about that @sapkra, we get quite a few messages and some fall through the cracks...

**Comment by chwzr** [comment] 2020-04-06 14:15
Hey,

first, im excited to here that Lib JitsiMeet is going to npm soon!
I understand both of you. But, some questions: is the backend doing some building on installation time or why is it crucial to embed id via script tag? 
I think client libs like this should be independent of the backend. Maybe just adding a check of backend/client version and throw error if incompatible versions are used.

Having a Client, with proper TypeScript Types setup is a big deal, as there are so much devs who then can use the jitsi ecosystem to generate lots of beautiful apps based on it. 

Can I do something to help speeding up this transition?

Cheers,
chwzr

**Comment by eloparco** [comment] 2020-11-15 10:52
Any ideas on how to do this (i.e. being able to use the library with only ```npm install lib-jitsi-meet```) if I have the possibility to change the library?
To explain it better, is there a solution to achieve this by making modifications to the library (```package.json``` maybe)? In this way I can publish it to a private npm registry and use it from there.
Thank you

**Comment by sapkra** [comment] 2020-11-26 00:33
@saghul @damencho Can you give an update on this topic? The last one is more than a year old.

**Comment by saghul** [comment] 2020-11-26 08:26
It's a bit complicated.

The only way we can realistically do this is with full-automation. Manual releases are out of the question since they'd introduce too much overhead.

I worked on that some time ago and set it up on the js-utils repo: https://github.com/jitsi/js-utils/blob/master/.github/workflows/autopublish.yml

The experiment worked, a new npm package is created on every push.

The problem is one needs to disable branch protection for GH Actions to be able to push without review. Alas skipping branch protection for GH Actions is not a thing, so I got stuck there. Then life happened and I haven't gotten back to it.

I really want it to happen. Sorry for the lack of updates.

**Comment by zamarawka** [comment] 2021-10-06 09:59
Sooo. Passing almost year since last update on this thread and maybe we got some updates here?

@saghul @sapkra 

But anyway, thanks for lib.

**Comment by saghul** [comment] 2021-10-06 10:16
The main reason why this doesn't happen is that we are concerned that people's applications will break if they don't update the library when we update the backend. While we don't change the public APIs often, there are lots of internal changes in the communication with the bridge that need to be in sync with the backend.

So I'm now leaning more towards "plan B": create a wrapper package that dynamically loads lib-jitsi-meet from the given domain. Adding TypeScript types to that hopefully makes it easier to consume, while making us less worried about no updates happening.

**Comment by saghul** [comment] 2022-11-10 08:02
Closing.

While we've added TS types (gradually) we still have no plans to publish this on npm.

**Closed by saghul** 2022-11-10 08:02 UTC
Labels: feature-request
