### ISSUE TITLE
videolocalTrack mute and unmute  fail

### ISSUE THREAD

**Issue by numsg** [jitsi/lib-jitsi-meet#1335] opened 2020-09-26 02:23 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
This is the first time I have used jitsi and found it very powerful.

Use lib jitsi meet / Doc / example.

Join the same meeting in two computers, using chrome 74

Add the video mute / unmute method. After one computer turns off the local video and then enables it, the remote video stream in the other computer cannot be recovered

first=>
if(localTracks[i].type === 'video') {
localTracks[i].mute();
}

then=>
if(localTracks[i].type === 'video') {
localTracks[i].unmute();
}

## Current behavior
---
Add the video mute / unmute method. After one computer turns off the local video and then enables it, the remote video stream in the other computer cannot be recovered
## Expected Behavior
---
Add the video mute / unmute method. After one computer turns off the local video and then enables it, the remote video stream in the other computer can be recovered

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---
1. Lib jitsi meet is the latest code
2. chrome version 74

**Comment by numsg** [comment] 2020-09-27 00:34
Do I need to do something in  TRACK_ MUTE_ CHANGED, 

Can someone help me? Thank you very much.

**Comment by numsg** [comment] 2020-09-27 08:26
use chrome://webrtc-internals/

Do the operation：
first： mute local video
Second: unmute local video

In SSRC_ 1279282941_ send (ssrc)
There is no upload stream

**Comment by huzaifahj** [comment] 2020-09-28 15:36
Seems to be related to the issue I submitted #1333 . Many others seeing similar problems.

**Comment by jallamsetty1** [comment] 2020-09-28 16:19
Is there a reason why you are trying with a much older version of Chrome ? Are you able to reproduce it with the latest version of Chrome ? Do you have p2p enabled in your config.js ?

**Comment by numsg** [comment] 2020-09-30 06:52
> Seems to be related to the issue I submitted #1333 . Many others seeing similar problems.

thank you very much！

**Comment by numsg** [comment] 2020-09-30 06:57
> Is there a reason why you are trying with a much older version of Chrome ? Are you able to reproduce it with the latest version of Chrome ? Do you have p2p enabled in your config.js ?

thank you very much！found the cause of the problem:

lib-jitsi-meet should use 
"lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#15dcc57424cc937290e1963b8eb402c1fcf48ccb"

use "lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#65df5b1da6bb6934e9d42f50d95aae0df6a5fd90"  not work

**Comment by numsg** [comment] 2020-09-30 07:02
Therefore, we need a one-to-one list of Lib jitsi meet and jitsi service versions

**Comment by huzaifahj** [comment] 2020-09-30 07:10
> > Is there a reason why you are trying with a much older version of Chrome ? Are you able to reproduce it with the latest version of Chrome ? Do you have p2p enabled in your config.js ?
> 
> thank you very much！found the cause of the problem:
> 
> lib-jitsi-meet should use
> "lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#15dcc57424cc937290e1963b8eb402c1fcf48ccb"
> 
> use "lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#65df5b1da6bb6934e9d42f50d95aae0df6a5fd90" not work

How did you use this lib jitsi meet version?

**Comment by sapkra** [comment] 2020-10-04 23:47
> Therefore, we need a one-to-one list of Lib jitsi meet and jitsi service versions

All repositories are tagged with the same jitsi version number. All of them will be compatible with each other. If you want to know the latest stable on meet.jit.si then you have to look for the latest stable release tag of jitsi-meet which is currently `jitsi-meet_5076` or `stable/jitsi-meet_5076`.

![image](https://user-images.githubusercontent.com/8087568/95029889-ec62bc00-06ab-11eb-98fa-1f4cc00e2536.png)

So you could use:

```json
{
  "lib-jitsi-meet": "github:jitsi/lib-jitsi-meet#jitsi-meet_5076"
}
```

Closing it now because it seems to be solved.

**Closed by sapkra** 2020-10-04 23:47 UTC
